/* tslint:disable:object-literal-key-quotes */

import { Injectable } from '@angular/core';
import { normalizePatientsData } from './patient.normalizers';
import { Observable } from 'rxjs';
import { of } from 'rxjs/observable/of';
import { delay, mapTo } from 'rxjs/operators';

const data = {
    'Count': 474,
    'Items': [
        {
            'Id': 10000104,
            'DisplayId': 'PT-10000104',
            'Name': {
                'FullName': '1Donna Monna',
                'First': '1Donna',
                'Middle': null,
                'Last': 'Monna',
            },
            'DateOfBirthday': '1952-05-07T00:00:00',
            'Address': {
                'AddressLine': '81 Pike Dr',
                'AddressLine2': '33',
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '81 Pike Dr, 33, Wayne, NJ, 07470',
                'AddressKey': '81 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '3434534634',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ADEL ASSISTED LIVING AND NURSING LLC',
            'LocationNpi': '1396869830',
            'Tags': [
                {
                    'Id': '969cd4cd63676b48c038121d8dc0dd6281f23c6c',
                    'Name': 'rental',
                },
                {
                    'Id': 'TA1d1fe497210a406b9c5d9100a8f11dd2',
                    'Name': 'test 2',
                },
                {
                    'Id': 'TA58f9cea36ca643b4b1aaa99d003d7ead',
                    'Name': 'folder',
                },
                {
                    'Id': 'TAb6da5a7b47fc47d69bc9809011985ba9',
                    'Name': 'need to review patient',
                },
            ],
            'Gender': {
                'Id': 2,
                'Text': 'Female',
                'Description': null,
            },
        },
        {
            'Id': 10000446,
            'DisplayId': 'PT-10000446',
            'Name': {
                'FullName': '226-1 test Resupply-Kidd',
                'First': '226-1',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-10-03T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '6M ENTERPRISES, P.A.',
            'LocationNpi': '1588694921',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000447,
            'DisplayId': 'PT-10000447',
            'Name': {
                'FullName': '226-2 test Resupply-Kidd',
                'First': '226-2',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-10-03T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '6M ENTERPRISES, P.A.',
            'LocationNpi': '1588694921',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000105,
            'DisplayId': 'PT-10000105',
            'Name': {
                'FullName': '2Alica Middle Name Correl',
                'First': '2Alica',
                'Middle': 'Middle Name',
                'Last': 'Correl',
            },
            'DateOfBirthday': '1952-05-08T00:00:00',
            'Address': {
                'AddressLine': '81 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '81 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '81 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '4564636346',
            ],
            'Status': {
                'Id': 2,
                'Text': 'Inactive',
                'Description': null,
            },
            'LocationName': 'ADEL ASSISTED LIVING AND NURSING LLC',
            'LocationNpi': '1396869830',
            'Tags': [
                {
                    'Id': '1aa344127ebc6cbc381c0ca79cef67da58191e26',
                    'Name': '123',
                },
                {
                    'Id': '52ee5b07b941c3659fd1d62c442c4f9b30ac953a',
                    'Name': 'test',
                },
                {
                    'Id': 'TAdfd0cd6d6b824d07b598dc69895e16bb',
                    'Name': 'ff',
                },
            ],
            'Gender': {
                'Id': 2,
                'Text': 'Female',
                'Description': null,
            },
        },
        {
            'Id': 10000084,
            'DisplayId': 'PT-10000084',
            'Name': {
                'FullName': 'A. Dale Hancock',
                'First': 'A. Dale',
                'Middle': null,
                'Last': 'Hancock',
            },
            'DateOfBirthday': '1943-11-07T00:00:00',
            'Address': {
                'AddressLine': '3308 W 5700 S',
                'AddressLine2': null,
                'City': 'Roy',
                'State': 'UT',
                'Zip': '84067',
                'FullAddress': '3308 W 5700 S, Roy, UT, 84067',
                'AddressKey': '3308 W 5700 S, Roy, UT, 84067',
            },
            'Phones': [
                '6874654654',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ACCURATE PRESCRIPTION SERVICES, LLC',
            'LocationNpi': '1992176648',
            'Tags': [
                {
                    'Id': '5918523dc479eb6f3080a65b7c76330a8d68f17a',
                    'Name': 'prescription',
                },
                {
                    'Id': 'TAb6da5a7b47fc47d69bc9809011985ba9',
                    'Name': 'need to review patient',
                },
            ],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000069,
            'DisplayId': 'PT-10000069',
            'Name': {
                'FullName': 'Aaan Aary Aary',
                'First': 'Aaan',
                'Middle': 'Aary',
                'Last': 'Aary',
            },
            'DateOfBirthday': '1999-12-28T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '5555555555',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ACCURATE PRESCRIPTION SERVICES, LLC',
            'LocationNpi': '1992176648',
            'Tags': [
                {
                    'Id': 'TAa18ecf91c7d24f0cbf407727df20e0ea',
                    'Name': 'New Taras Tag',
                },
            ],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000381,
            'DisplayId': 'PT-10000381',
            'Name': {
                'FullName': 'Aaron-643 Combi',
                'First': 'Aaron-643',
                'Middle': null,
                'Last': 'Combi',
            },
            'DateOfBirthday': '2004-02-04T00:00:00',
            'Address': {
                'AddressLine': '81 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '81 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '81 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '3463463463',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '1780 MANAGEMENT LLC',
            'LocationNpi': '1922246446',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000121,
            'DisplayId': 'PT-10000121',
            'Name': {
                'FullName': 'Aban Axel Axel',
                'First': 'Aban',
                'Middle': 'Axel',
                'Last': 'Axel',
            },
            'DateOfBirthday': '1955-08-10T00:00:00',
            'Address': {
                'AddressLine': '81 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '81 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '81 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '0000000000',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ADEL ASSISTED LIVING AND NURSING LLC',
            'LocationNpi': '1396869830',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000204,
            'DisplayId': 'PT-10000204',
            'Name': {
                'FullName': 'Abby Hunter',
                'First': 'Abby',
                'Middle': null,
                'Last': 'Hunter',
            },
            'DateOfBirthday': '1952-05-07T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '6666656666',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'MERCER PRIMARY CARE ASSOCIATES LLC',
            'LocationNpi': '1528070901',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000052,
            'DisplayId': 'PT-10000052',
            'Name': {
                'FullName': 'Abery T. Olsen',
                'First': 'Abery',
                'Middle': 'T.',
                'Last': 'Olsen',
            },
            'DateOfBirthday': '1940-08-15T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '5555555555',
                '6666666666;666666',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ACCURATE PRESCRIPTION SERVICES, LLC',
            'LocationNpi': '1992176648',
            'Tags': [
                {
                    'Id': 'TA57b0fe7a41434636a5bc2fd0779d84da',
                    'Name': 'vip patient',
                },
            ],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000226,
            'DisplayId': 'PT-10000226',
            'Name': {
                'FullName': 'Abery T. Olsen',
                'First': 'Abery',
                'Middle': 'T.',
                'Last': 'Olsen',
            },
            'DateOfBirthday': '1940-05-15T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1231232132',
                '1232132132;1111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ACCURATE PRESCRIPTION SERVICES, LLC',
            'LocationNpi': '1992176648',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000117,
            'DisplayId': 'PT-10000117',
            'Name': {
                'FullName': 'Abetta Nortson',
                'First': 'Abetta',
                'Middle': null,
                'Last': 'Nortson',
            },
            'DateOfBirthday': '1952-05-27T00:00:00',
            'Address': {
                'AddressLine': '81 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '81 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '81 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ADEL ASSISTED LIVING AND NURSING LLC',
            'LocationNpi': '1396869830',
            'Tags': [],
            'Gender': {
                'Id': 2,
                'Text': 'Female',
                'Description': null,
            },
        },
        {
            'Id': 10000116,
            'DisplayId': 'PT-10000116',
            'Name': {
                'FullName': 'Abigail Orneson',
                'First': 'Abigail',
                'Middle': null,
                'Last': 'Orneson',
            },
            'DateOfBirthday': '2013-01-30T00:00:00',
            'Address': null,
            'Phones': [],
            'Status': {
                'Id': 2,
                'Text': 'Inactive',
                'Description': null,
            },
            'LocationName': null,
            'LocationNpi': null,
            'Tags': [],
            'Gender': {
                'Id': 0,
                'Text': 'Unknown',
                'Description': null,
            },
        },
        {
            'Id': 10000118,
            'DisplayId': 'PT-10000118',
            'Name': {
                'FullName': 'Abigail Torrentson',
                'First': 'Abigail',
                'Middle': null,
                'Last': 'Torrentson',
            },
            'DateOfBirthday': '1999-12-28T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '3463463463',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ACCURATE PRESCRIPTION SERVICES, LLC',
            'LocationNpi': '1992176648',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000114,
            'DisplayId': 'PT-10000114',
            'Name': {
                'FullName': 'Abonrell Farrel',
                'First': 'Abonrell',
                'Middle': null,
                'Last': 'Farrel',
            },
            'DateOfBirthday': '1939-04-03T00:00:00',
            'Address': {
                'AddressLine': '81 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '81 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '81 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '9999999999',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'ACCURATE PRESCRIPTION SERVICES, LLC',
            'LocationNpi': '1992176648',
            'Tags': [],
            'Gender': {
                'Id': 2,
                'Text': 'Female',
                'Description': null,
            },
        },
        {
            'Id': 10000453,
            'DisplayId': 'PT-10000453',
            'Name': {
                'FullName': 'ACHM R-4 test Resupply-Kidd',
                'First': 'ACHM R-4',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-10-16T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '6M ENTERPRISES, P.A.',
            'LocationNpi': '1588694921',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000454,
            'DisplayId': 'PT-10000454',
            'Name': {
                'FullName': 'ACHM R-5 test Resupply-Kidd',
                'First': 'ACHM R-5',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-10-16T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '6M ENTERPRISES, P.A.',
            'LocationNpi': '1588694921',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000437,
            'DisplayId': 'PT-10000437',
            'Name': {
                'FullName': 'ACHM-1 test Resupply-Kidd',
                'First': 'ACHM-1',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2012-01-02T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '6M ENTERPRISES, P.A.',
            'LocationNpi': '1588694921',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000438,
            'DisplayId': 'PT-10000438',
            'Name': {
                'FullName': 'ACHM-2 test Resupply-Kidd',
                'First': 'ACHM-2',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '1999-12-27T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '8710 EMGE ROAD OPERATIONS LLC',
            'LocationNpi': '1063694529',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000439,
            'DisplayId': 'PT-10000439',
            'Name': {
                'FullName': 'ACHM-3 test Resupply-Kidd',
                'First': 'ACHM-3',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '1999-12-27T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '8710 EMGE ROAD OPERATIONS LLC',
            'LocationNpi': '1063694529',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000440,
            'DisplayId': 'PT-10000440',
            'Name': {
                'FullName': 'ACHM-4 test Resupply-Kidd',
                'First': 'ACHM-4',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-09-28T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '8710 EMGE ROAD OPERATIONS LLC',
            'LocationNpi': '1063694529',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000441,
            'DisplayId': 'PT-10000441',
            'Name': {
                'FullName': 'ACHM-5 test Resupply-Kidd',
                'First': 'ACHM-5',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-09-28T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': 'A PLUS ASSISTED CARE',
            'LocationNpi': '1306910377',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000444,
            'DisplayId': 'PT-10000444',
            'Name': {
                'FullName': 'ACHM-6 test Resupply-Kidd',
                'First': 'ACHM-6',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-10-02T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '6M ENTERPRISES, P.A.',
            'LocationNpi': '1588694921',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
        {
            'Id': 10000445,
            'DisplayId': 'PT-10000445',
            'Name': {
                'FullName': 'ACHM-7 test Resupply-Kidd',
                'First': 'ACHM-7',
                'Middle': 'test',
                'Last': 'Resupply-Kidd',
            },
            'DateOfBirthday': '2018-10-02T00:00:00',
            'Address': {
                'AddressLine': '1 Pike Dr',
                'AddressLine2': null,
                'City': 'Wayne',
                'State': 'NJ',
                'Zip': '07470',
                'FullAddress': '1 Pike Dr, Wayne, NJ, 07470',
                'AddressKey': '1 Pike Dr, Wayne, NJ, 07470',
            },
            'Phones': [
                '1111111111',
            ],
            'Status': {
                'Id': 1,
                'Text': 'Active',
                'Description': null,
            },
            'LocationName': '6M ENTERPRISES, P.A.',
            'LocationNpi': '1588694921',
            'Tags': [],
            'Gender': {
                'Id': 1,
                'Text': 'Male',
                'Description': null,
            },
        },
    ],
};

@Injectable()
export class PatientEndpointsMockService {

    constructor() {
    }

    public getPatients(): Observable<any> {
        const mockData = of(null);

        return mockData.pipe(
            delay(1000),
            mapTo(normalizePatientsData(data)),
        );
    }
}
