export const INVENTORY_TRANSFER = {

    RESET_PAIR_LIST: 'RESET_PAIR_LIST',
    SET_PAIR_LIST: 'SET_PAIR_LIST',

    RESET_PAIR_CURRENT: 'RESET_PAIR_CURRENT',
    SET_PAIR_CURRENT: 'SET_PAIR_CURRENT'

}

export const INVENTORY_RECEIVE = {

    RESET_PAIR_LIST: 'RESET_PAIR_LIST',
    SET_PAIR_LIST: 'SET_PAIR_LIST',

    RESET_PAIR_CURRENT: 'RESET_PAIR_CURRENT',
    RESET_PURCHASE_ORDER: 'RESET_PURCHASE_ORDER',
    SET_PAIR_CURRENT: 'SET_PAIR_CURRENT'

}
