export const QUICKSHIP = {

    // SHIP ITEMS
    RESET_QUICKSHIP_STATE: 'RESET_QUICKSHIP_STATE',

    RESET_ORDER_SHORT_INFO: 'RESET_ORDER_SHORT_INFO',
    SET_ORDER_SHORT_INFO: 'SET_ORDER_SHORT_INFO',

    RESET_PATIENT_INFO: 'RESET_PATIENT_INFO',
    SET_PATIENT_INFO: 'SET_PATIENT_INFO',

    RESET_SHIP_ITEMS: 'RESET_SHIP_ITEMS',
    SET_SHIP_ITEMS: 'SET_SHIP_ITEMS',
    ATTACH_COMPONENTS: 'ATTACH_COMPONENTS',
    SET_AMOUNT_FROM_INVENTORY: 'SET_AMOUNT_FROM_INVENTORY',
    SET_DELIVERY_METHOD_TO_ALL: 'SET_DELIVERY_METHOD_TO_ALL',
    DIVIDE_NOT_MULTIPLE: 'DIVIDE_NOT_MULTIPLE',

    RESET_ITEM_PROPERTIES: 'RESET_ITEM_PROPERTIES',

    ADD_QUICKSHIP_ITEMS: 'ADD_QUICKSHIP_ITEMS',
    DELETE_SHIP_ITEM: 'DELETE_SHIP_ITEM',
    UPDATE_SHIP_ITEM: 'UPDATE_SHIP_ITEM',
    UPDATE_SHIP_COMPONENT: 'UPDATE_SHIP_COMPONENT',

    // PICK FROM INVENTORY
    SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
    SET_CURRENT_COMPONENTS: 'SET_CURRENT_COMPONENTS',
    RESET_CURRENT_PRODUCT: 'RESET_CURRENT_PRODUCT',

    CLEAR_PROCESSIGN_ITEM: 'CLEAR_PROCESSIGN_ITEM',
    UPDATE_PROCESSIGN_ITEM: 'UPDATE_PROCESSIGN_ITEM',
    FULFILL_PROCESSIGN_ITEM: 'FULFILL_PROCESSIGN_ITEM',

    SET_LOCATION_FROM: 'SET_LOCATION_FROM',
    RESET_LOCATION_FROM: 'RESET_LOCATION_FROM',

    SET_ANY_LOCATION_FROM: 'SET_ANY_LOCATION_FROM',

    SET_LOOKUP_PROPERTY: 'SET_LOOKUP_PROPERTY',
    SET_NEXT_KEY_PROPERTY: 'SET_NEXT_KEY_PROPERTY',
    SET_STATUS_PROPERTY: 'SET_STATUS_PROPERTY',
    SET_BARCODE_PROPERTY: 'SET_BARCODE_PROPERTY',
    DETERMINE_ACTIVE_PROPERTY: 'DETERMINE_ACTIVE_PROPERTY',

    ADD_PICKED_ITEMS: 'ADD_PICKED_ITEMS',
    ADD_SEPARATED_PICKED_ITEM: 'ADD_SEPARATED_PICKED_ITEM',
    RESET_PICKED_ITEMS: 'RESET_PICKED_ITEMS',
    DELETE_PICKED_ITEM: 'DELETE_PICKED_ITEM',

    ADD_LINKED_ITEMS: 'ADD_LINKED_ITEMS',
    UPDATE_LINKED_ITEM: 'UPDATE_LINKED_ITEM',
    REMOVE_LINKED_ITEM: 'REMOVE_LINKED_ITEM',

    UPDATE_OR_CREATE_LOCATION_PRODUCTS_COUNTER: 'UPDATE_OR_CREATE_LOCATION_PRODUCTS_COUNTER',
    RESET_TEMP_COUNT_LOCATION_PRODUCTS_COUNTER: 'RESET_TEMP_COUNT_LOCATION_PRODUCTS_COUNTER',
    RESET_SELECTED_COUNT_LOCATION_PRODUCTS_COUNTER: 'RESET_SELECTED_COUNT_LOCATION_PRODUCTS_COUNTER',
    SHIFT_FROM_TEMP_TO_SELECTED_COUNT: 'SHIFT_FROM_TEMP_TO_SELECTED_COUNT',
    RESET_ALL_TEMP_COUNTS: 'RESET_ALL_TEMP_COUNTS',
    PREFILL_SELECTED_QTY_BY_LOCATION: 'PREFILL_SELECTED_QTY_BY_LOCATION',
    CLEAR_PREFILL_SELECTED_QTY: 'CLEAR_PREFILL_SELECTED_QTY'
};

export const DICTIONARIES = {
    SET_DELIVERY_METHOD_DICTIONARIES: 'SET_DELIVERY_METHOD_DICTIONARIES',
    SET_DELIVERY_COMPANIES_DICTIONARY: 'SET_DELIVERY_COMPANIES_DICTIONARY'
};
